### ISSUE TITLE
Please publish your package particle4dev:sass for Windows

### ISSUE THREAD

**Issue by avital** [particle4dev/meteor-sass#14]
Hi!

This package has binary dependencies, and we wanted to give you a heads up that Meteor 1.1, with support for Windows will be released in a few days.

Now is the time to publish your package for Windows!

It should be very straightforward -- we've added new build machines that run Windows that you can access with the `meteor admin get-machine` command. This is the same as you've done before for the other architectures we support.

For complete directions on how to publish your package for Windows, visit https://github.com/meteor/meteor/wiki/Publishing-a-package-with-binary-dependencies-for-the-Windows-preview

On behalf of the Meteor team,
@stubailo, @Slava and @avital.

P.S. This is an automated message based on our database of package authors.

**Comment by illusionfield** [comment]
I tried it but I got error message:
```
C:\Users\Krisztina\AppData\Local\.meteor\packages\meteor-tool\1.0.45\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:278
                                                throw(ex);
                                                      ^
Error: failed to make temporary directory in /C/Users/KRISZT~1/AppData/Local/Temp
    at make (C:\Users\Krisztina\AppData\Local\.meteor\packages\meteor-tool\1.0.45\mt-os.windows.x86_32\tools\files.js:614:11)
    at Object.files.mkdtemp (C:\Users\Krisztina\AppData\Local\.meteor\packages\meteor-tool\1.0.45\mt-os.windows.x86_32\tools\files.js:616:13
)
    at Command.main.registerCommand.name [as func] (C:\Users\Krisztina\AppData\Local\.meteor\packages\meteor-tool\1.0.45\mt-os.windows.x86_32\tools\commands-packages.js:591:26)
    at C:\Users\Krisztina\AppData\Local\.meteor\packages\meteor-tool\1.0.45\mt-os.windows.x86_32\tools\main.js:1345:23
```

...BUT this repo is cloned to the package directory:
```sh
git clone https://github.com/particle4dev/meteor-sass.git packages\meteor-sass
meteor add particle4dev:sass
```
it compiles without any error.

I prepeare a new version from package.js: https://gist.github.com/illusionfield/c16f349aa2abb0f3b4d8
I think with this modification I can compile and publish the package.
I tested the new package.js, working any architecture (win,osx,linux)
First I would like pinging @particle4dev ask his opinion. If he find it ok. than let's go.

**Comment by illusionfield** [comment]
I tried it:  ``meteor admin get-machine os.windows.x86_32``

but I got error message:
```
Logged in as illusionfield. Thanks for being a Meteor developer!                
C:\Windows\system32>meteor whoami                                               
illusionfield                                                                   
C:\Windows\system32>meteor publish-for-arch particle4dev:sass@2.0.1             
                                                                                
C:\Windows\System32\config\systemprofile\AppData\Local\.meteor\packages\meteor-t
ool\1.0.45\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:278
                                                                                
                                                throw(ex);                      
                                                      ^                         
Error: failed to make temporary directory in /C/Windows/TEMP                    
    at make (C:\Windows\System32\config\systemprofile\AppData\Local\.meteor\pack
ages\meteor-tool\1.0.45\mt-os.windows.x86_32\tools\files.js:614:11)             
    at Object.files.mkdtemp (C:\Windows\System32\config\systemprofile\AppData\Lo
cal\.meteor\packages\meteor-tool\1.0.45\mt-os.windows.x86_32\tools\files.js:616:
13)                                                                             
    at Command.main.registerCommand.name [as func] (C:\Windows\System32\config\s
ystemprofile\AppData\Local\.meteor\packages\meteor-tool\1.0.45\mt-os.windows.x86
_32\tools\commands-packages.js:591:26)                                          
    at C:\Windows\System32\config\systemprofile\AppData\Local\.meteor\packages\m
eteor-tool\1.0.45\mt-os.windows.x86_32\tools\main.js:1345:23       
C:\Windows\system32> 
```

**Comment by stubailo** [comment]
@illusionfield - we're going to look into this ASAP!

**Comment by particle4dev** [comment]
Hey guys,
Good new ! I finally can publish my package for Windows. It suddenly works for me. Maybe i can close this issue.
Thanks everyone
